network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      addresses:
       - 192.168.0.5/24
      dhcp4: no
      routes:
       - to: 0.0.0.0/0
         via: 192.168.0.1 # gateway address
         on-link: true
       - to: 0.0.0.0/0
         via: 192.168.0.1 # gateway address
         table: 900
       - to: 192.168.0.5
         via: 0.0.0.0
         scope: link
         table: 900
      routing-policy:
        - from: 192.168.0.5
          table: 900
    eth1:
      addresses:
       - 192.168.1.5/24
      dhcp4: no
      routes:
       - to: 0.0.0.0/0
         via: 192.168.1.1 # gateway address
         on-link: true
       - to: 0.0.0.0/0
         via: 192.168.1.1 # gateway address
         table: 999
       - to: 192.168.1.5
         via: 0.0.0.0
         scope: link
         table: 999
      routing-policy:
        - from: 192.168.1.5
          table: 999
